### ISSUE TITLE
Is it possible to add SVG elements like rect circle as drop element 

### ISSUE THREAD

**Issue by manirikhi** [vuegg/vuegg#13]
When i try to add SVG element in basic element config then it is not working.
i tried below

  {
    'name': 'svg',
    'type': 'svg',
    'egglement': true,
    'containegg': true,
    'iconName': 'icon',
    'width': 50,
    'height': 44.44,
    'styles': {},
    'classes': {},
    'children': [
      {
        'type': 'circle',
        'attrs': {
          'cx': 50,
          'cy': 50,
          'stroke': 'green'
        }
      }
    ]
  }
could you please help? thanks

**Comment by alxpez** [comment]
Well, this is not really an issue with **vuegg** (since SVGs are not even a feature... at the moment), but happy to give you some tip on your personal endeavour.

Try this out:
``` js
{
    'name': 'svg',
    'type': 'svg',
    'egglement': true,
    'wrappegg': true,
    'width': 100,
    'height': 100,
    'styles': {},
    'classes': {},
    'children': [
      {
        'type': 'circle',
        'attrs': {
          'cx': '50%',
          'cy': '50%',
          'r': '50%',
          'stroke': 'green',
          'fill': 'yellow'
        }
      }
    ]
  },
```
Check out some [documentation](https://www.w3schools.com/graphics/svg_circle.asp) that may help you
