### ISSUE TITLE
Sorry about That , i want to know atob where is come from 

### ISSUE THREAD

**Issue by chinanf-boy** [vuegg/vuegg#18]
`store.replaceState(newState(JSON.parse(atob(project))))`
https://sourcegraph.com/github.com/vuegg/vuegg/-/blob/client/src/store/actions/projectAct.js#L141

**Comment by abdullah** [comment]
@chinanf-boy It is related to global [`atob`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/atob) function which is given by window. You can check it.
