### ISSUE TITLE
Elements can't be deleted

### ISSUE THREAD

**Issue by mfcarneiro** [vuegg/vuegg#33]
I'm using some features of Vuegg without problem but after putting a toggle button, the application started to bug and the delete functionality is not working properly.

After copying and paste the layout from another screen and creating a new page, the deleting behavior stopped work and now I can't even deleting the toggle component and nor the new page. 

I can delete others components together, but the toggle persists.

I'm using Manjaro Linux and Vuegg web version on Mozilla and Opera and both is not working.

**Comment by alxpez** [comment]
Hi @mfcarneiro,

Could you include the steps to reproduce this behaviour?
Also, could you be more specific with the elements that are giving you problems? (I'm unsure as to what you refer with "_toggle button_").

If you could include a video link or a GIF, that would be great to fully understand the problem.

Thanks!

**Comment by mfcarneiro** [comment]
i'm facing a problem with the video recorder, but I'll provide for you certainly.

It is a problem with toggle itself, others components working together fine, just the toggle in my "page" does not erase.

**Comment by mfcarneiro** [comment]
Hi @alxpez 

I fixed the problem with the recorder but de gif mode does not work at all sweat_smile

I've make others tests on the [video](https://github.com/vuegg/vuegg/files/2013313/vuegg.deleting.error.zip) to be sure.

Inside of the div, the toggle was deleted with no problem, but alone, I'm not allowed to do the same.

I hope that's help with something.

Thanks ;)

**Comment by alxpez** [comment]
@mfcarneiro I haven't been able to reproduce that behaviour, I've tested it by doing  all sorts of crazy copy/pasting, moving in between containers, duplicating pages... nothing. (this is a macbook pro, tested on chrome and firefox).

The only thing I have in mind is testing it in a linux machine I have at home (ubuntu), I'm guessing it could be related with the OS.

I'm out of ideas. Let me know if you can try to reproduce it on a different OS, say windows, macOS or any other linux distro.

Cheers!

**Comment by mfcarneiro** [comment]
I'll try on another pc because here I don't have windows hahahah :sweat_smile: 

Maybe the interface of linux can mess up vuegg? I'm using i3wm, for the record.

I'll keep in touch if I found something else.

Thanks you for the attention ;)

**Comment by alxpez** [comment]
Hey @mfcarneiro, sorry for the delay.
I haven't been able to reproduce this weird behaviour on my ubuntu machine. I'll be closing this issue now, but ping me if there's any new around this problem.

Cheers mate
