### ISSUE TITLE
[Feat] vuegg as standalone component

### ISSUE THREAD

**Issue by krzysztof-koszula** [vuegg/vuegg#36]
Is it possible to use it as component, not whole project?
Best regards

**Comment by alxpez** [comment]
Not really sure what you mean by that.

My guess is that you're referring to the move-resize functionality, which at the moment is fairly coupled with many of the application features.

Nonetheless I'm confident that extracting it as a standalone component is possible and shouldn't be very complex.

Feel free to share your progress if you decide to take this feature into your own hands.

Cheers!
