### ISSUE TITLE
[Bug] Why downloaded zip folder is empty?

### ISSUE THREAD

**Issue by theshashiverma** [vuegg/vuegg#44]
I open your and create a basic design by dropping some elements. But when I download the file the zip i get is empty..why so?

**Comment by DoffD** [comment]
hi @theshashiverma,
Were you able to resolve the issue? I'm actually waiting for your issue and https://github.com/vuegg/vuegg/issues/42 to be resolved. I would really appreciate it if you can share the solution. Thank you in advance.

**Comment by OmgImAlexis** [comment]
Same issue here.

@alxpez any ideas?

**Comment by ZhengHuang-20** [comment]
Same issue here.
@alxpez any ideas?
