### ISSUE TITLE
Github User authentication question.

### ISSUE THREAD

**Issue by 625781186** [vuegg/vuegg#47]
Login successful, but invalid.
Click login again ,  and the authentication window closes automatically
![image](https://user-images.githubusercontent.com/30521429/62511955-8d57ac00-b848-11e9-999c-e3c076d86396.png)

### ajax `http://localhost:8080/api/get-access-token`  is right?

![image](https://user-images.githubusercontent.com/30521429/62513808-d4956b00-b84f-11e9-9de6-7bb90a703ff7.png)

I'm try return my token , it's OK.

![image](https://user-images.githubusercontent.com/30521429/62514318-749fc400-b851-11e9-904d-788b617201b8.png)

**Comment by alxpez** [comment]
Do you have any adBlocker extension on your browser?
That could cause some weird behaviour, otherwise idk.

**Comment by alxpez** [comment]
I can't reproduce the error on a Chrome browser (even with the nanoAdBlocker active). Let me know.
