### ISSUE TITLE
how to add :before and :after css in mockcomponents.js？

### ISSUE THREAD

**Issue by zhenjingbo** [vuegg/vuegg#48]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by alxpez** [comment]
@zhenjingbo  `:before` and `:after` selectors are not implemented within vuegg (at least not right now). If you have a workaround that might be applying this functionality feel free to share it or open a PR from your branch.

Thanks!
