### ISSUE TITLE
No files when i download the project 

### ISSUE THREAD

**Issue by shahabgohar** [vuegg/vuegg#50]
**Describe the bug**
> so i made a web page and when i download it then it does not contain any thing

**To Reproduce**

> Steps to reproduce the behavior:

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Expected behavior**
> A clear and concise description of what you expected to happen.

**Actual Behavior**
> A clear and concise description of what it's actually happening.

**Your environment**
> - OS & version [e.g. iOS]
> - Browser name & version [e.g. chrome, safari]
> - Vuegg version [e.g. 22]

**Additional context**
> How has this bug affected you? What were you trying to accomplish?

**Comment by ZhengHuang-20** [comment]
![image](https://user-images.githubusercontent.com/61463534/77245816-742b3080-6c5c-11ea-8ec9-e19ed837884e.png)
when i download .zip , the file of zip was nothing. my cmd show the image。
