### ISSUE TITLE
Typo in client editor component

### ISSUE THREAD

**Issue by laghim** [vuegg/vuegg#51]
**Describe the bug/issue**
Not a bug exactly, but found typos in your client editor component MenuToggle.vue. Instead of "default", there is written "dafault". This might affect the functionality. 

**Screenshots**
> 
![image](https://user-images.githubusercontent.com/22259701/84032926-c4cf4180-a9a0-11ea-901c-e42ec6e0ad64.png)

**Comment by alxpez** [comment]
Thanks for reporting @laghim!
Indeed a typo, that could be affecting functionality within vuegg's interface.

Feel free to open a PR with a fix if you have time, it'd be highly appreciated.
Thanks!

**Comment by laghim** [comment]
Hi @alxpez - I just opened a PR for this. Thank you too!
