### ISSUE TITLE
Bug: Github Connect Button results in Not Found 404

### ISSUE THREAD

**Issue by natesire** [vuegg/vuegg#60]
This is an absolutely amazing tool. I want to help contribute.

Bug:

404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: iad1::849rq-1601923566864-a39434d08507

NOTE: vuegg.now.sh might be available. Click here to learn how to assign it to a project.

**To Reproduce**
Click the Github Icon

**Expected behavior**
Connect to Github

**Comment by alxpez** [comment]
Yeah, the free tier server where I had vuegg deployed, took it down due to a version upgrade. I haven't had the time to read through the docs, fix/rewrite the server configuration changes and deploy vuegg again.

You can still download the code and run it locally?
